service: single-point-processing-example
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/AmazonRekognitionReadOnlyAccess

functions:
  imgProcessor:
    handler: index.handler
    events:
      - s3:
          bucket: !Ref animalsBucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: raw/
          existing: true
          forceDeploy: true
    destinations:
      onSuccess:
        type: sns
        arn:
          Ref: SuccessTopic
      onFailure:
        type: sns
        arn:
          Ref: FailureTopic

resources:
  Resources:
    animalsBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        AccessControl: Private
        BucketName: 
          Fn::Join:
            - "-"
            - - animals-bucket
              - Fn::Select:
                - 4
                - Fn::Split:
                  - "-"
                  - Fn::Select:
                    - 2
                    - Fn::Split:
                      - "/"
                      - !Ref AWS::StackId
    SuccessTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: SuccessTopic
    FailureTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: FailureTopic
